version: '2'

services:     

  web: 
    build: .
    ports: 
      - "8080:8080"
    volumes: 
      - .:/go/src/github.com/jetbasrawi/app
    links: 
      - redis

  redis:  
    image: redis
    command: redis-server --appendonly yes
    volumes: 
      - ./workstation_multiservice_redis_data:/data




